import { chromium } from "playwright";
const browser = await chromium.launch();
const page = await browser.newPage({ viewport: { width: 1400, height: 950 } });
await page.goto("http://localhost:3000");
await page.getByText("What are you measuring?").waitFor();
await page.getByRole("button", { name: /Suspension cells/ }).click();
await page.getByRole("button", { name: /Choose markers/ }).click();
const card = page.locator("div.rounded-lg").filter({ has: page.getByText("Immune lineage backbone (human)", { exact: true }) }).first();
await card.getByRole("button", { name: /^Add \d+ markers/ }).click();
await page.getByRole("button", { name: /Balance panel/ }).first().click();
await page.getByRole("button", { name: "Balance panel", exact: true }).click();
await page.waitForTimeout(1500);
const tiles = await page.locator("main .flex.h-24 > div").evaluateAll((els) => els.map((e) => [e.title.slice(0, 40), e.firstElementChild.className.split(" ").filter((c) => c.startsWith("bg-")).join(",")]));
console.log(tiles.length, "tiles");
console.log(tiles.filter((t) => !t[1].includes("slate-100")).map((t) => t.join(" | ")).join("\n"));
console.log(tiles.slice(0, 3), tiles.slice(-3));
await page.locator("main .flex.h-24").screenshot({ path: "scripts/shots/strip-suspension.png" });
await browser.close();
